export const ERROR_CODE = Object.freeze({
  GARMENT_NOT_FOUND: "GARMENT_NOT_FOUND",
  GARMENT_CREATE_FAILED: "GARMENT_CREATE_FAILED",
  GARMENT_UPDATE_FAILED: "GARMENT_UPDATE_FAILED",

  CASE_NOT_FOUND: "CASE_NOT_FOUND",
  CASE_CREATE_FAILED: "CASE_CREATE_FAILED",
  CASE_UPDATE_FAILED: "CASE_UPDATE_FAILED",
  CASE_DELETE_FAILED: "CASE_DELETE_FAILED",

  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  LOCATION_DUPLICATE: "LOCATION_DUPLICATE",
  LOCATION_CREATE_FAILED: "LOCATION_CREATE_FAILED",
  LOCATION_DELETE_FAILED: "LOCATION_DELETE_FAILED",

  CHECKIN_PARTIAL_NOT_FOUND: "CHECKIN_PARTIAL_NOT_FOUND",
  CHECKOUT_ONLY_RESOLVE: "CHECKOUT_ONLY_RESOLVE",

  DB_QUERY_FAILED: "DB_QUERY_FAILED",
} as const);

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
